text_to_terminal = {
    'arg': ['$Arg'],
    'argument': ['$Arg'],
    'the': ['$The'],
    'true': ['$True'],
    'correct': ['$True'],
    'false': ['$False'],
    'incorrect': ['$False'],
    'wrong': ['$False'],
    'and': ['$And'],
    'but': ['$And'],
    'or': ['$Or'],
    'nor': ['$Or'],
    'not': ['$Not'],
    'n"t': ['$Not'],
    'n\'t': ['$Not'],
    'all': ['$All'],
    'both': ['$All'],
    'any': ['$Any'],
    'a': ['$Any', '$AtLeastOne'],
    'one of': ['$Any'],
    'none': ['$None'],
    'not any': ['$None'],
    'neither': ['$None'],
    'no': ['$None', '$Int'],
    'is': ['$Is'],
    'are': ['$Is'],
    'be': ['$Is'],
    'comes': ['$Is'],
    'come': ['$Is'],
    'appears': ['$Is'],
    'appear': ['$Is'],
    'as': ['$Is'],
    'occurs': ['$Is'],
    'occur': ['$Is'],
    'is stated': ['$Is'],
    'is found': ['$Is'],
    'said': ['$Is'],
    'is identified': ['$Is'],
    'are identified': ['$Is'],
    'is used': ['$Is'],
    'is placed': ['$Is'],
    'exist': ['$Exists'],
    'exists': ['$Exists'],
    'immediately': ['$Direct'],
    'right': ['$Direct', '$Right'],
    'directly': ['$Direct'],
    'last': ['$Last'],
    'final': ['$Last'],
    'ending': ['$Last'],
    'another': ['$AtLeastOne'],
    'because': ['$Because'],
    'since': ['$Because'],
    'if': ['$Because'],
    'equal': ['$Equals'],
    'equals': ['$Equals'],
    '=': ['$Equals'],
    '==': ['$Equals'],
    'same as': ['$Equals'],
    'same': ['$Equals'],
    'identical': ['$Equals'],
    'exactly': ['$Equals'],
    'different than': ['$NotEquals'],
    'different': ['$NotEquals'],
    'less than': ['$LessThan'],
    'smaller than': ['$LessThan'],
    '<': ['$LessThan'],
    'at most': ['$AtMost'],
    'no larger than': ['$AtMost'],
    'less than or equal': ['$AtMost'],
    'within': ['$AtMost', '$Within'],
    'no more than': ['$AtMost'],
    '<=': ['$AtMost'],
    'at least': ['$AtLeast'],
    'no less than': ['$AtLeast'],
    'no smaller than': ['$AtLeast'],
    'greater than or equal': ['$AtLeast'],
    '>=': ['$AtLeast'],
    'more than': ['$MoreThan'],
    'greater than': ['$MoreThan'],
    'larger than': ['$MoreThan'],
    '>': ['$MoreThan'],
    'is in': ['$In'],
    'in': ['$In'],
    'contains': ['$Contains'],
    'contain': ['$Contains'],
    'containing': ['$Contains'],
    'include': ['$Contains'],
    'includes': ['$Contains'],
    'says': ['$Contains'],
    'states': ['$Contains'],
    'mentions': ['$Contains'],
    'mentioned': ['$Contains'],
    'referred': ['$Contains'],
    'refers': ['$Contains'],
    'is referring to': ['$Contains'],
    ',': ['$Separator', []],
    '/': ['$Separator'],
    '\'s': ['$Possessive'],
    'number': ['$Count', '$NumberNER'],
    'length': ['$Count'],
    'count': ['$Count'],
    'pair': ['$Tuple'],
    'tuple': ['$Tuple'],
    'they': ['$ArgXListAnd', '$ArgXListAnd'],
    'them': ['$ArgXListAnd', '$ArgXListAnd'],
    'entities': ['$ArgXListAnd'],
    'eachother': ['$EachOther'],
    'each other': ['$EachOther'],
    'token': ['$Token', '$Word'],
    'word': ['$Word'],
    'words': ['$Word'],
    'term': ['$Word'],
    'terms': ['$Word'],
    'tokens': ['$Word'],
    'phrase': ['$Word'],
    'phrases': ['$Word'],
    'string': ['$Word'],
    'character': ['$Char'],
    'characters': ['$Char'],
    'letter': ['$Char'],
    'letters': ['$Char'],
    'upper': ['$Upper'],
    'uppercase': ['$Upper'],
    'upper case': ['$Upper'],
    'all caps': ['$Upper'],
    'all capitalized': ['$Upper'],
    'lower': ['$Lower'],
    'lowercase': ['$Lower'],
    'lower case': ['$Lower'],
    'capital': ['$Capital'],
    'capitals': ['$Capital'],
    'capitalized': ['$Capital'],
    'starts with': ['$StartsWith'],
    'start with': ['$StartsWith'],
    'starting with': ['$StartsWith'],
    'ends with': ['$EndsWith'],
    'end with': ['$EndsWith'],
    'ending with': ['$EndsWith'],
    'to the left of': ['$Left'],
    'left': ['$Left'],
    'in front of': ['$Left'],
    'before': ['$Left'],
    'precedes': ['$Left'],
    'preceding': ['$Left'],
    'followed by': ['$Left'],
    'to the right of': ['$Right'],
    'behind': ['$Right'],
    'after': ['$Right'],
    'preceded by': ['$Right'],
    'follows': ['$Right'],
    'following': ['$Right'],
    'next': ['$Within'],
    'apart': ['$Apart'],
    'away': ['$Apart'],
    'sentence': ['$Sentence'],
    'tweet' : ['$Sentence'],
    'text': ['$Sentence'],
    'it': ['$Sentence'],
    'between': ['$Between'],
    'in between': ['$Between'],
    'sandwiched': ['$Between'],
    'enclosed': ['$Between'],
    'Between': ['$Between'],
    'admist': ['$Between'],
    'in the middle of': ['$Between'],
    'person': ['$PersonNER'],
    'people': ['$PersonNER'],
    'location': ['$LocationNER'],
    'locations': ['$LocationNER'],
    'place': ['$LocationNER'],
    'places': ['$LocationNER'],
    'date': ['$DateNER'],
    'dates': ['$DateNER'],
    'numbers': ['$NumberNER'],
    'organization': ['$OrganizationNER'],
    'organizations': ['$OrganizationNER'],
    'company': ['$OrganizationNER'],
    'companies': ['$OrganizationNER'],
    'agency': ['$OrganizationNER'],
    'agencies': ['$OrganizationNER'],
    'institution': ['$OrganizationNER'],
    'institutions': ['$OrganizationNER'],
    'political': ['$NorpNER'],
    'politician': ['$NorpNER'],
    'religious': ['$NorpNER'],
    'x': ['$ArgX'],
    '<s>': ['$ArgX'],
    'subj': ['$ArgX'],
    'subject': ['$ArgX'],
    'y': ['$ArgY'],
    '<o>': ['$ArgY'],
    'obj': ['$ArgY'],
    'object': ['$ArgY'],
    'there': ['$There'],
    'by': ['$By'],
    'which': ['$Which'],
    'the number of': ['$Numberof'],
    'of': ['$Of'],
    'links': ['$Link'],
    'link': ['$Link'],
    'connects': ['$Link'],
    'connect': ['$Link'],
    'sandwich': ['$SandWich'],
    'sandwiches': ['$SandWich'],
    'is in': '$In',
    'one of': '$Any',
    'not any': '$None',
    'is stated': '$Is',
    'is found': '$Is',
    'is identified': '$Is',
    'are identified': '$Is',
    'is used': '$Is',
    'is placed': '$Is',
    'same as': '$Equals',
    'different than': '$NotEquals',
    'less than': '$LessThan',
    'smaller than': '$LessThan',
    'at most': '$AtMost',
    'no larger than': '$AtMost',
    'less than or equal': '$AtMost',
    'no more than': '$AtMost',
    'at least': '$AtLeast',
    'no less than': '$AtLeast',
    'no smaller than': '$AtLeast',
    'greater than or equal': '$AtLeast',
    'more than': '$MoreThan',
    'greater than': '$MoreThan',
    'larger than': '$MoreThan',
    'is referring to': '$Contains',
    'each other': '$EachOther',
    'upper case': '$Upper',
    'all caps': '$Upper',
    'all capitalized': '$Upper',
    'lower case': '$Lower',
    'starts with': '$StartsWith',
    'start with': '$StartsWith',
    'starting with': '$StartsWith',
    'ends with': '$EndsWith',
    'end with': '$EndsWith',
    'ending with': '$EndsWith',
    'to the left of': '$Left',
    'in front of': '$Left',
    'followed by': '$Left',
    'to the right of': '$Right',
    'preceded by': '$Right',
    'in between': '$Between',
    'in the middle of': '$Between',
    'the number of': '$Numberof'
}