# Generated by Django 2.1.7 on 2020-03-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triggerexplanation',
            unique_together={('annotation', 'trigger_id', 'start_offset', 'end_offset')},
        ),
    ]
