# Generated by Django 2.1.7 on 2020-05-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200419_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='server.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set(),
        ),
    ]
