# Generated by Django 2.1.7 on 2020-05-23 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0005_auto_20200513_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='explanation_type',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Natural Language Explanation'), (3, 'Trigger Explanation')], default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='acquire',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='setting',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='batch',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='setting',
            name='embedding',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='epoch',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='setting',
            name='history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='nounchunk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='onlinelearning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='server.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('user', 'project')},
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['project', 'user'], name='user_project_settings_index'),
        ),
        migrations.RemoveField(
            model_name='setting',
            name='explanation',
        ),
    ]
