# Generated by Django 2.1.7 on 2020-06-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200525_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedentityannotation',
            name='user_provided',
        ),
        migrations.AddField(
            model_name='annotation',
            name='user_provided',
            field=models.BooleanField(default=False),
        ),
    ]
