# Generated by Django 2.1.7 on 2020-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20200612_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='user_provided',
            field=models.BooleanField(default=False),
        ),
    ]
