# Generated by Django 2.1.7 on 2020-08-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20200721_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedentityannotationhistory',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ner_history', to='server.Annotation'),
        ),
        migrations.AddField(
            model_name='relationextractionannotationhistory',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_history', to='server.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='server.Task'),
        ),
    ]
