# Generated by Django 2.1.7 on 2020-09-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20200813_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedentityannotationhistory',
            name='user_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationextractionannotationhistory',
            name='user_provided',
            field=models.BooleanField(default=False),
        ),
    ]
